package model.direct;

// Generated 18:12:01 17/08/2011 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * Nouns generated by hbm2java
 */
public class Nouns implements java.io.Serializable {

	private NounsId id;
	private BigDecimal score;

	public Nouns() {
	}

	public Nouns(NounsId id, BigDecimal score) {
		this.id = id;
		this.score = score;
	}

	public NounsId getId() {
		return this.id;
	}

	public void setId(NounsId id) {
		this.id = id;
	}

	public BigDecimal getScore() {
		return this.score;
	}

	public void setScore(BigDecimal score) {
		this.score = score;
	}

}
