package model.direct;

// Generated 18:12:01 17/08/2011 by Hibernate Tools 3.3.0.GA

/**
 * VerbsId generated by hbm2java
 */
public class VerbsId implements java.io.Serializable {

	private String lhs;
	private String rhs;

	public VerbsId() {
	}

	public VerbsId(String lhs, String rhs) {
		this.lhs = lhs;
		this.rhs = rhs;
	}

	public String getLhs() {
		return this.lhs;
	}

	public void setLhs(String lhs) {
		this.lhs = lhs;
	}

	public String getRhs() {
		return this.rhs;
	}

	public void setRhs(String rhs) {
		this.rhs = rhs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VerbsId))
			return false;
		VerbsId castOther = (VerbsId) other;

		return ((this.getLhs() == castOther.getLhs()) || (this.getLhs() != null
				&& castOther.getLhs() != null && this.getLhs().equals(
				castOther.getLhs())))
				&& ((this.getRhs() == castOther.getRhs()) || (this.getRhs() != null
						&& castOther.getRhs() != null && this.getRhs().equals(
						castOther.getRhs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLhs() == null ? 0 : this.getLhs().hashCode());
		result = 37 * result
				+ (getRhs() == null ? 0 : this.getRhs().hashCode());
		return result;
	}

}
